import * as z from "zod";

export const formSchema = z.object({
  firstName: z.string().min(2, "First name must be at least 2 characters"),
  lastName: z.string().min(2, "Last name must be at least 2 characters"),
  email: z.string().email("Invalid email address"),
  phone: z.string().min(10, "Phone number must be at least 10 digits"),
  currentLocation: z.string().min(2, "Current location is required"),
  desiredLocation: z.string().min(2, "Desired location is required"),
  branchOfService: z.enum([
    "Army",
    "Navy",
    "Air Force",
    "Marines",
    "Coast Guard",
    "Space Force",
  ]),
  rank: z.string().min(1, "Rank is required"),
  payGrade: z.string().min(1, "Pay grade is required"),
  dateEnteredService: z.date(),
  primaryMOS: z.string().min(1, "Primary MOS/AFSC/Rate is required"),
  secondaryMOS: z.string().optional(),
  clearanceLevel: z.enum([
    "None",
    "Confidential",
    "Secret",
    "Top Secret",
    "TS/SCI",
  ]),
  separationDate: z.date(),
  terminalLeaveDate: z.date(),
  tapsStatus: z.enum([
    "Not Started",
    "In Progress",
    "Completed",
    "Exempt",
  ]),
  retirementEligible: z.enum(["Yes", "No"]),
  medicalSeparation: z.enum(["Yes", "No"]),
  vaClaimStatus: z.enum([
    "Not Started",
    "Planning BDD",
    "Planning Standard Claim",
    "In Progress",
  ]),
  giBillPlans: z.enum([
    "Plan to Use",
    "Already Using",
    "Transfer to Dependents",
    "Not Planning to Use",
  ]),
  vaHomeLoanInterest: z.enum(["Yes", "No"]),
  lifeInsuranceConversion: z.enum(["Yes", "No"]),
  careerInterests: z.array(z.enum([
    "Government/Federal",
    "Defense Contractor",
    "Private Sector",
    "Entrepreneurship",
    "Law Enforcement",
    "Other",
  ])),
  educationPlans: z.enum([
    "None",
    "Certificate/Technical",
    "Associate's",
    "Bachelor's",
    "Master's",
    "Doctorate",
  ]),
  skillbridgeInterest: z.enum(["Yes", "No"]),
  woundedWarrior: z.enum(["Yes", "No"]),
  disabilityEvaluation: z.enum(["Yes", "No"]),
  caregiverRequirements: z.enum(["Yes", "No"]),
  spouseEmployment: z.enum(["Yes", "No"]),
  resumeHelp: z.enum(["Yes", "No"]),
  interviewPrep: z.enum(["Yes", "No"]),
  housingAssistance: z.enum(["Yes", "No"]),
  financialPlanning: z.enum(["Yes", "No"]),
  healthcareNavigation: z.enum(["Yes", "No"]),
});